export default {
  primary: '#7b1fa2',
  primaryDark: '#6a1b9a',
  primaryLight: '#e1bee7',
  accent: '#ffffff',
  success: '#76ff03',
  warning: '#ffd740',
  danger: '#ff1744',
  neutralLight: '#eeeeee',
  neutralDark: '#9E9E9E',
  light: '#FFFFFF',
  dark: '#000000',
  paper: '#FFFFFF',
  transparent: 'transparent',
};
